name: image_loading_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
